# Generated by Django 4.1.7 on 2023-03-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='driver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.driver'),
        ),
    ]
