# Generated by Django 4.1.7 on 2023-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_truck_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='prime_location',
        ),
        migrations.AddField(
            model_name='driver',
            name='currentLat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='driver',
            name='currentLongit',
            field=models.FloatField(default=None),
        ),
    ]
